name: Pipeline Tests
description: 'Test'

runs:
    using: "composite"
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v4

      - name: Run Automation Tests API
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:execution
