name: Pipeline Tests

on:
  push:
      branch: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v4
      - name: Run Automation Tests API/E2E
        uses: cypress-io/github-action@v6
      - name: Login
      - run: npm run cy:login
