name: Pipeline Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v4

      - name: Run Automation Tests API
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:execution
